name: Update Docker Volume

on:
  push:
    branches:
      - master  # Ou a branch que você está usando

jobs:
  update-volume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: sudo apt-get install docker-compose

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker Image
      run: docker pull wordpress:latest

    - name: Update Volume with New Content
      run: |
        docker run --rm -v crackudosmangas_data:/data -v $(pwd)/path/to/updated-content:/content alpine sh -c "cp -r /content/* /data/"

    - name: Restart Docker Containers
      run: |
        docker-compose down
        docker-compose up -d
